config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups, except: [:destroy, :show] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_members
  has_many :users, through: :group_members
  has_many :messages
  accepts_nested_attributes_for :group_members
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true, unless: ->(message){message.image.present?}
  validates :image, presence: true, unless: ->(message){message.body.present?}

  mount_uploader :image, ImageUploader

  def params_for_json
    {user_name: self.user.name, created_at: self.created_at, body: self.body, image: self.image}
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  # association
  has_many :group_members
  has_many :groups, through: :group_members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
  # sign_upのときに、nameも許可する
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  # accoutのeditのときに、nameも許可する
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:edit, :update]

  def index
    @groups = Group.all
  end
  def new
    @group = Group.new
  end
  def create
    Group.create(group_params)
    redirect_to :root
  end
  def edit
  end
  def update
    @group.update(group_params)
    redirect_to :root
  end

  private
  def find_group
    @group = Group.find(params[:id])
  end
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_group
  def index
    @message = Message.new
    @messages = @group.messages
    respond_to do |format|
      format.html
      format.json {
        messages = @messages.map do |message|
          message.params_for_json
        end
        render json: messages
      }
    end
  end
  def create
    message = Message.new(create_params)
    if message.save
      respond_to do |format|
        format.html { redirect_to_messages_index }
        format.json { render json: message.params_for_json }
      end
    else
      render json: ""
    end
  end

  private
  def find_group
    @group = Group.find(params[:group_id])
  end
  def create_params
    params.require(:message).permit(:body, :image).merge(group_id: @group.id, user_id: current_user.id)
  end
  def redirect_to_messages_index
    redirect_to group_messages_path(@group)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    users = User.where(['name LIKE ?', "%#{params[:input]}%"])
    render json: users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def user_is_member?(group_id, user_id)
    GroupMember.find_by(group_id: group_id, user_id: user_id).present? ? true : false
  end
end

app/views/common/_sidebar.html.haml
.sidebar
  .sidebar-nav
    .sidebar-nav__user-name
      %span #{current_user.name}
    .sidebar-nav__settings
      = link_to new_group_path do
        .fa.fa-pencil-square-o.fa-inverse.fa-lg
      = link_to edit_user_registration_path do
        .fa.fa-cog.fa-inverse.fa-lg
  .sidebar-body
    -groups.each do |group|
      =link_to group_messages_path(group) do
        .joined-group
          .joined-group__group-name #{group.name}
          .joined-group__group-message huge

app/views/groups/_member.html.haml
.chat-group-user.clearfix
  %span{name: "#{member.id}"} #{member.name}
  %a.chat-group-user__remove-btn 削除
  %input.group_user_ids{name: "group[user_ids][]", type: "hidden", value: "#{member.id}"}

app/views/groups/_sidebar.html.haml
.sidebar
  .sidebar-nav
    .sidebar-nav__user-name
      %span #{current_user.name}
    .sidebar-nav__settings
      = link_to new_group_path do
        .fa.fa-pencil-square-o.fa-inverse.fa-lg
      = link_to edit_user_registration_path do
        .fa.fa-cog.fa-inverse.fa-lg
  .sidebar-body
    -groups.each do |group|
      =link_to group_path(group) do
        .joined-group
          .joined-group__group-name #{group.name}
          .joined-group__group-message huge

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =form_for @group, html: {id: "edit_chat_group_#{@group.id}", class: "edit_chat_group"} do |f|
    -f.hidden_field :utf8, value: "✓"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :グループ名, class: "chat-group-form__label"
      .chat-group-form__field--right
        =f.text_field :name, id: "chat_group_name", class: "chat-group-form__input", placeholder: "グループ名を入力してください", value: @group.name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          =text_field_tag nil, nil, id: "user-search-field", class: "chat-group-form__input", placeholder: "追加したいユーザー名を入力してください"
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :チャットメンバー, class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          = render partial: "member", collection: @group.users
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit class: "chat-group-form__action-btn", value: "Save", "data-disable-with": "Save"

app/views/groups/index.html.haml
.contents
  =render partial: "common/sidebar", locals: {groups: current_user.groups}

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =form_for @group, html: {id: "new_chat_group",class: "new_chat_group"} do |f|
    -f.hidden_field :utf8, value: "✓"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :グループ名, class: "chat-group-form__label"
      .chat-group-form__field--right
        =f.text_field :name, id: "chat_group_name", class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          =text_field_tag nil, nil, id: "user-search-field", class: "chat-group-form__input", placeholder: "追加したいユーザー名を入力してください"
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :チャットメンバー, class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            %span{name: "#{current_user.id}"} #{current_user.name}
            %input.group_user_ids{name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}"}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit class: "chat-group-form__action-btn", value: "Save", "data-disable-with": "Save"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if notice
      %p.notice=notice
    - if alert
      %p.alert=alert
    = yield

app/views/messages/_group-info.html.haml
%h2 #{@group.name}
%span Members:
-users.each do |user|
  %span= user.name

app/views/messages/_message.html.haml
.message
  .message__detail
    %span.message__user-name #{message.user.name}
    %span.message__sended-date #{message.created_at}
  - if message.body.present?
    %span.message__content #{message.body}
  -else
    =image_tag message.image, alt: ""

app/views/messages/index.html.haml
.contents
  =render partial: "common/sidebar", locals: {groups: current_user.groups}
  .chat
    .chat-nav
      .chat-nav__left
        =render partial: "group-info", locals: {users: @group.users}
      .chat-nav__right
        =link_to "Edit", edit_group_path(@group)
    .chat-body
      =render @group.messages
    .chat-footer
      =form_for @message, url: group_messages_path(@group), html: {class: "new-message"} do |f|
        =f.text_field :body, class: "new-message__input-form", placeholder: "type a message"
        =f.label :image do
          %i.fa.fa-image.fa-lg
          =f.file_field :image, class: "new-message__file-form"
        =f.submit class: "new-message__submit-button", value: "Send"